### PR TITLE
Tests/osmosis adapter

### PR DESCRIPTION
**Pull request by Kayanski**
This PR aims at testing and adding tests to the Osmosis adapter.

The following PR : https://github.com/AbstractSDK/cw-orchestrator/pull/150 should be merged before the current one can be merged.
Dependencies should be changed in patch : [adapters/Cargo.toml](adapters/Cargo.toml)

## Tasks

- [x] Create an osmosis-test-tube testing implementation for the adapter contract
- [ ] Create TESTNET tests for actual live pools (and scraped ans data)

### CODE REVIEW

**Comment by CyberHoward** [comment]
@Buckram123 could this branch be useful to you for osmosis adapter testing?

**Comment by Buckram123** [comment]
> @Buckram123 could this branch be useful to you for osmosis adapter testing?

I had ultra-small test for osmosis swap: 
https://github.com/AbstractSDK/abstract/blob/6806edb7d6035ba024c499b976cd2802c3d0be3b/modules/contracts/adapters/dex/tests/osmosis_swap.rs#L191-L206

But this one looks much better! Would like to update it and get merged

**Comment by Kayanski** [comment]
> > @Buckram123 could this branch be useful to you for osmosis adapter testing?
> 
> I had ultra-small test for osmosis swap:
> 
> https://github.com/AbstractSDK/abstract/blob/6806edb7d6035ba024c499b976cd2802c3d0be3b/modules/contracts/adapters/dex/tests/osmosis_swap.rs#L191-L206
> 
> But this one looks much better! Would like to update it and get merged

Go ahead obviously :)

**Comment by Buckram123** [comment]
@Kayanski, this and #115 solves the same issue: that we need proxy address on osmosis execution. But taking two different solution to this(solution in this PR doesn't cover queries yet), so I decided to just merge `osmosis.rs` file with tests in there: https://github.com/AbstractSDK/abstract/commit/8052a7e56516110b42164d2c33a8df5517c74f0e

Are you okay to close this one?

**Comment by Kayanski** [comment]
> @Kayanski, this and #115 solves the same issue: that we need proxy address on osmosis execution. But taking two different solution to this(solution in this PR doesn't cover queries yet), so I decided to just merge `osmosis.rs` file with tests in there: [8052a7e](https://github.com/AbstractSDK/abstract/commit/8052a7e56516110b42164d2c33a8df5517c74f0e)
> 
> Are you okay to close this one?

Yes, I have not worked extensively enough on this PR so go ahead ;) Take the tests with you though yeah

**Comment by Buckram123** [comment]
Tests moved to #115

**Pull request closed without merging**
