### PR TITLE
Improve ContractEntry construction

### PR DESCRIPTION
**Pull request by Buckram123**
This PR implements FromStr for ContractEntry.
# Checklist

- CI is green.
- Changelog updated.

### CODE REVIEW

**Review by adairrr — APPROVED** [review]
Lgtm!

**Comment by Buckram123** [comment]
@adairrr wdyt, do we need to remove TryFrom<String> for UncheckedEntry?

**Comment by Buckram123** [comment]
> @adairrr wdyt, do we need to remove TryFrom for UncheckedEntry?

And if yes, how we can do it harmless

**Comment by adairrr** [comment]
> > @adairrr wdyt, do we need to remove TryFrom for UncheckedEntry?
> 
> And if yes, how we can do it harmless

Is there a reason to?

**Comment by Buckram123** [comment]
> > > @adairrr wdyt, do we need to remove TryFrom for UncheckedEntry?
> > 
> > 
> > And if yes, how we can do it harmless
> 
> Is there a reason to?

Sorry, meant to say remove TryFrom<String> in favor of TryFrom<&str> because references are always preferable, and we don't benefit from owning a string anyway. In addition can save few bytes in wasms

**Comment by Buckram123** [comment]
> Shouldn't we keep the From implementation ?

Is there's a reason to support both string and string slice?

**Comment by CavernPerson** [comment]
Not really no

**Comment by Kayanski** [comment]
Not really no

**Review by CyberHoward — APPROVED** [review]

**Comment by CyberHoward** [comment]
module tests failing, will check after merging this.

**Pull request merged**
