### PR TITLE
Adapters should have crates.io dependencies

### PR DESCRIPTION
**Pull request by Kayanski**
This PR aims at allowing users to import abstract from a crates.io dependency and adapter from this git monorepo

### CODE REVIEW

**Comment by CyberHoward** [comment]
I'll just remove the path deps from adapters when publishing the crate

**Comment by CyberHoward** [comment]
because if we keep the deps to crates the code won't compile

**Comment by CyberHoward** [comment]
We're not merging this, we'll keep the adapter path deps for development and remove them when we create a release.

**Comment by CyberHoward** [comment]
Does that work? I think the adapter integrations will also require it, sucks really hard tho

**Comment by Kayanski** [comment]
Why are you saying this ? This works as is now, using abstract 0.16.1

**Comment by CyberHoward** [comment]
Fixed in #14

**Pull request closed without merging**
