### PR TITLE
Improve modules not found during install error And other API errors

### PR DESCRIPTION
**Pull request by Buckram123**
Even though we improved errors on queries inside apps by adding API object, we still miss information about what method exactly failed. This PR aims to improve it by adding method_name inside error.

### Checklist

- [x] CI is green.
- [ ] Changelog updated.

### CODE REVIEW

**Review by cyberhoward — APPROVED** [review]
Very cool, didn't know about that crate!!

**Comment by Buckram123** [comment]
> Very cool, didn't know about that crate!!

Do we want to expand errors like that for AnsHost queries as well?

**Comment by CyberHoward** [comment]
> > Very cool, didn't know about that crate!!
> 
> Do we want to expand errors like that for AnsHost queries as well?

Yeah could be nice!

**Comment by Buckram123** [comment]
> Yeah could be nice!

Added!

**Review by cyberhoward — APPROVED** [review]

**Pull request merged**
