### PR TITLE
Apps schema updates

### PR DESCRIPTION
**Pull request by Buckram123**
- Bumped apps versions
- Generated new schemas
- Fixed publish-schema scripts

# Checklist

- CI is green.
- Changelog updated.

### CODE REVIEW

**Comment by Buckram123** [comment]
not gonna bother fixing "beta/clippy", since they are fixed in #21

**Comment by CyberHoward** [comment]
could you check out #17 ? We can now use the write api successfully (used to be impossible due to generics)

I think we should only generate the top-level json schema, the FE will need to parse it (like a normal contract)

**Comment by CyberHoward** [comment]
@Buckram123 what was the point of this PR. Do we still want to merge this?

**Comment by Buckram123** [comment]
> @Buckram123 what was the point of this PR. Do we still want to merge this?

It's just schema updates and schema scripts fixes. Gonna update this one later

**Review by CyberHoward — APPROVED** [review]

**Pull request merged**
